import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional

from app.core.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


def send_alert_email(
    city: str,
    aqi_value: int,
    recipient: Optional[str] = None
) -> bool:
    """
    Send email alert when AQI exceeds threshold.

    Args:
        city: City name with high AQI
        aqi_value: Current AQI value
        recipient: Email recipient (defaults to ALERT_EMAIL)

    Returns:
        True if email sent successfully, False otherwise
    """
    recipient = recipient or settings.ALERT_EMAIL

    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        logger.warning(f"SMTP credentials not configured. Would send alert to {recipient} for {city} AQI={aqi_value}")
        return False

    subject = f"🚨 Air Quality Alert: {city} - AQI {aqi_value}"

    body = f"""
    <html>
    <body style="font-family: Arial, sans-serif;">
        <h2 style="color: #ef4444;">⚠️ Unhealthy Air Quality Alert</h2>

        <div style="background-color: #fef2f2; padding: 20px; border-left: 4px solid #ef4444; margin: 20px 0;">
            <p><strong>City:</strong> {city}</p>
            <p><strong>AQI Level:</strong> {aqi_value}</p>
            <p><strong>Time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>

        <h3>Health Recommendations:</h3>
        <ul>
            <li>Avoid outdoor activities</li>
            <li>Keep windows closed</li>
            <li>Use air purifiers indoors</li>
            <li>Wear N95 masks if going outside</li>
            <li>Monitor symptoms if you have respiratory conditions</li>
        </ul>

        <p style="color: #6b7280; font-size: 12px; margin-top: 30px;">
            This is an automated alert from TerraPulse AI Environmental Monitoring System.
        </p>
    </body>
    </html>
    """

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.SMTP_USER
        msg["To"] = recipient

        msg.attach(MIMEText(body, "html", "utf-8"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.sendmail(settings.SMTP_USER, recipient, msg.as_string())

        logger.info(f"✅ Alert email sent to {recipient} for {city} (AQI: {aqi_value})")
        return True

    except smtplib.SMTPAuthenticationError as e:
        logger.error(f"SMTP Authentication failed: {e}")
        return False
    except smtplib.SMTPException as e:
        logger.error(f"SMTP error occurred: {e}")
        return False
    except Exception as e:
        logger.error(f"Failed to send alert email: {e}")
        return False


def send_forecast_alert_email(
    city: str,
    current_aqi: int,
    predicted_aqi: int,
    confidence: float,
    recipient: Optional[str] = None
) -> bool:
    """Send an early warning email when forecasted AQI exceeds threshold."""
    recipient = recipient or settings.ALERT_EMAIL

    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        logger.warning(
            "SMTP credentials not configured. Would send forecast alert to "
            f"{recipient} for {city}: current={current_aqi}, predicted={predicted_aqi}"
        )
        return False

    subject = f"TerraPulse AI Forecast Alert: {city} may reach AQI {predicted_aqi}"

    body = f"""
    <html>
    <body style="font-family: Arial, sans-serif;">
        <h2 style="color: #dc2626;">TerraPulse AI Forecast Alert</h2>

        <div style="background-color: #fff7ed; padding: 20px; border-left: 4px solid #f97316; margin: 20px 0;">
            <p><strong>City:</strong> {city}</p>
            <p><strong>Current AQI:</strong> {current_aqi}</p>
            <p><strong>Predicted AQI in 24 hours:</strong> {predicted_aqi}</p>
            <p><strong>Model confidence:</strong> {round(confidence * 100)}%</p>
            <p><strong>Alert threshold:</strong> {settings.AQI_ALERT_THRESHOLD}</p>
            <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>

        <h3>Recommended Early Actions:</h3>
        <ul>
            <li>Notify sensitive groups before AQI crosses the danger threshold</li>
            <li>Increase city monitoring frequency</li>
            <li>Reduce outdoor activity planning for vulnerable users</li>
            <li>Prepare purifier and mask guidance for affected areas</li>
        </ul>

        <p style="color: #6b7280; font-size: 12px; margin-top: 30px;">
            This ML-based early warning was generated by TerraPulse AI.
        </p>
    </body>
    </html>
    """

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.SMTP_USER
        msg["To"] = recipient

        msg.attach(MIMEText(body, "html", "utf-8"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.sendmail(settings.SMTP_USER, recipient, msg.as_string())

        logger.info(
            f"Forecast alert email sent to {recipient} for {city} "
            f"(current={current_aqi}, predicted={predicted_aqi})"
        )
        return True

    except smtplib.SMTPAuthenticationError as e:
        logger.error(f"SMTP Authentication failed: {e}")
        return False
    except smtplib.SMTPException as e:
        logger.error(f"SMTP error occurred: {e}")
        return False
    except Exception as e:
        logger.error(f"Failed to send forecast alert email: {e}")
        return False
